### ISSUE TITLE
ParseHtmlToJson loses folder structure

### ISSUE THREAD

**Issue by dys-solutions** [microsoft/dynamics365f-o-custom-help#1]
The destination folder contains all json files in the root. The folder structure of the source is not mapped into destination folder. This causes the help to refer to the wrong html file.

**Comment by MargoC** [comment]
Thanks, we're working on that issue.

**Comment by edupont04** [comment]
Hello @dys-solutions 
Thank you for your feedback! We have published a new version of the toolkit with a bunch of bugfixes, including the one you pointed out. Please check out the new version from the master branch, and read about the new and changed tools here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/help/custom-help-toolkit
