### ISSUE TITLE
ParseHtmlToJson CLI support

### ISSUE THREAD

**Issue by dys-solutions** [microsoft/dynamics365f-o-custom-help#2]
Please add CLI support for the ParseHtmlToJson tool.

**Comment by MargoC** [comment]
Thanks for the feature suggestion. We'll add it to our backlog.

**Comment by edupont04** [comment]
Hello @dys-solutions 
Thank you for your feedback!  We have published a new version of the toolkit with a bunch of bugfixes, including the one you pointed out (ParseHtmlToJson has been renamed ConvertHtmlToJson and is now a CLI tool). Please check out the new version from the master branch, and read about the new and changed tools here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/help/custom-help-toolkit
