### ISSUE TITLE
Debugger.Launch() in AzureSearchCustomHelp.Client

### ISSUE THREAD

**Issue by BenPoell** [microsoft/dynamics365f-o-custom-help#5]
I had the issue that the debugger always popped up and therefore the custom help tab / the client session freezes when opening.
After some code review I found out that there is a Debugger.Launch() in AzureSearchCustomHelp.Client.searchResult(), which triggers the Debugger everytime there is a search request. 
![image](https://user-images.githubusercontent.com/24900930/42809047-e7ced0be-89b4-11e8-8f9b-89511d7f629f.png)

**Comment by edupont04** [comment]
Hello @BenPoell 

Thank you for your feedback!  We have published a new version of the toolkit with a bunch of bugfixes, including the one you pointed out (Debugger.Launch statement is removed). Please check out the new version from the master branch, and read about the new and changed tools here: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/help/custom-help-toolkit
